### ISSUE TITLE
bogus license file

### ISSUE THREAD

**Issue by Fabian-Gruenbichler** [slp/capng#4]
[`LICENSE-BSD-3-Clause`](https://github.com/slp/capng/blob/master/LICENSE-BSD-3-Clause) seems to be the result of downloading the HTML page https://github.com/rust-vmm/vm-memory/blob/main/LICENSE-BSD-3-Clause , I guess the intention was downloading and committing the raw file.

I am also not sure if the contained copyright statement (`Copyright 2017 The Chromium OS Authors. All rights reserved.`) applies to this crate/repository as well or not, and would appreciate a clarification.

(currently working on packaging virtiofsd for Debian, and this is on of its transitive dependencies)

**Comment by slp** [comment]
@Fabian-Gruenbichler Thanks a lot for letting me know. I've created a PR with a fix and will update the crate right away.

**Comment by Fabian-Gruenbichler** [comment]
thanks for the super fast response :)
